### ISSUE TITLE
[FR] include Pi1541 zero hardware

### ISSUE THREAD

**Issue by SvOlli** [SukkoPera/OpenC64WarpSpeed#2]
Hello!

Seeing the [Epyx Fastload with Pi1541 Zero](https://www.sordan.ie/product/753/pi1541-zero--epyx-fastload-hat--case---commodore-64-128-vic20/), I thought that this was a good idea, except the instead of the crappy Epyx Fastload a WarpSpeed should have been used for the cartridge part.

How about creating a "pi1541"-branch that will include WarpSpeed and a Pi1541 zero on one PCB? I can already offer my [try on the schematics](https://github.com/SukkoPera/OpenC64WarpSpeed/files/5550160/OpenC64WarpSpeed.zip) for this combined effort for now. For later, I plan to work on an updated firmware that will support changing directories and mounting disk images. But I'm pretty sure that my take on layouting the PCB will be very suboptimal.

The current version of the Pi1541 schematic consists of
- Option B, so additional drives can be used as well (also needed for SRQ, see below)
- support as SRQ added as output only (hopefully 1581 mode will then support fast serial)
- instead of 2xIEC connectors a 2x6 pinhead is used to save space
- I2C pins added for SSD1306 display
- piezo buzzer removed, as support in pi1541 code has been removed when compiling for pi zero

**Comment by SukkoPera** [comment]
Nice idea, but I'm not interested in working on it at the moment. Feel free to fork the repo and take your chance at it, just pay attention to the license. This deserves to be a separate project in any case.
